# SETTING PORTAL
sm.portal.dev=false
sm.portal.nameId = 10465620540
sm.portal.nameDisplay = Usuario Prueba
sm.portal.email = usuario@dominio.pe
log.proceso.enabled = true


# CMIS
sm.portal.cmis.name = iproviderRepositoryDev
sm.portal.cmis.key = iproviderRepositoryDev
cfg.portal.cmis.name = iproviderRepositoryDev
cfg.portal.cmis.key = iproviderRepositoryDev
destination.cmis = IPROVIDER_CMIS

#Folder ECM
cfg.folder.ecm = ArchivosSunat

#ClaveSol
cfg.sunat.user = IPROVIDE
cfg.sunat.pass = iPROVIDE1

#URL PORTAL
##CAMBIAR AQUI!!!
sm.portal.url = https://flpnwc-a8vkr95ktt.dispatcher.br1.hana.ondemand.com/sites/iprovider#Shell-home 
#cfg.portal.url = https://flpnwc-f9iyf5gkk6.dispatcher.eu2.hana.ondemand.com/sites?siteId=3468528f-ff5a-4864-9f95-4f9874f1a34d&evictCache=true#Shell-home
cfg.portal.url = https://copeinca-com.launchpad.cfapps.us10.hana.ondemand.com/site?siteId=3d31aaf6-15cf-4509-969a-b5b3754404e4#Shell-home

cfg.portal.url.public.oc = https://copeinca-com.launchpad.cfapps.us10.hana.ondemand.com/site?siteId=3d31aaf6-15cf-4509-969a-b5b3754404e4#Dynamic-display?sap-ui-app-id-hint=saas_approuter_iproviderpublicacionoccompras
cfg.portal.url.public.oc.proveedor = https://copeinca-com.launchpad.cfapps.us10.hana.ondemand.com/site?siteId=3d31aaf6-15cf-4509-969a-b5b3754404e4#Dynamic-display?sap-ui-app-id-hint=saas_approuter_iproviderpublicacionocprovee


#WEBSERVICE PDF-XML COMPROBATE DE RETENCION
cfg.retencion.ws.url = http://qas.incloud.la:9998/services/S3getFilesCopeinca


#NOTIFICACIONES CONSULTAS URL
cfg.notificacion.consulta.url = iprovider@copeinca.com.pe


# HANA (CLOUD) DB
# JPA / HIBERNATE
spring.jpa.properties.hibernate.format_sql=false
spring.datasource.driver-class-name=com.sap.db.jdbc.Driver
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.HANARowStoreDialect
#spring.datasource.url = jdbc:sap://zeus.hana.prod.eu-central-1.whitney.dbaas.ondemand.com:24312/?user=IPROVIDER_DEV_BCK&currentSchema=IPROVIDER_DEV&password=CfgInicio03$$&encrypt=true&ValidateCertificate=true
#spring.datasource.username = IPROVIDER_DEV_BCK\
#spring.datasource.password = CfgInicio07$$
spring.datasource.url = jdbc:sap://d3f93497-9f99-4a55-a276-ecbbe062713f.hna0.prod-us10.hanacloud.ondemand.com:443/?user=IPROVIDER_DEV_CF&currentSchema=IPROVIDER_DEV_CF&password=Inicio01$$&encrypt=true&ValidateCertificate=true
spring.datasource.username = IPROVIDER_DEV_CF
spring.datasource.password = Inicio01$$
#destination.email = SEND_MAIL_IPROVIDER
destination.email = https://cpi-prd-cf-dds57f4m.it-cpi019-rt.cfapps.us10-002.hana.ondemand.com/cxf/iproviderMail

# PRIMARY DATA SOURCE
# HANA (CLOUD) DB
# (= create, update, none)
spring.jpa.hibernate.ddl-auto = update
spring.jta.enabled = true
spring.jpa.show-sql = true

# Hikari will use the above plus the following to setup connection pooling
spring.datasource.hikari.minimumIdle=2
spring.datasource.hikari.maximumPoolSize=10
spring.datasource.hikari.idleTimeout=3000
spring.datasource.hikari.poolName=SpringBootJPAHikariCP
spring.datasource.hikari.maxLifetime=20000
spring.datasource.hikari.connectionTimeout=3000


#destinations

#DEV? 300
#destination.rfc.profit=CFG_DEST_RFC

#QAS 520
#destination.rfc.profit=CFG_DEST_RFC_QAS_520
destination.rfc.profit=CFG_DEST_RFC_QAS_500
#destination.rfc.profitgr=CFG_DEST_RFC_QAS_500_CLONING
destination.rfc.profitgr=CFG_DEST_RFC_CLONING


#------------------------------------------

#CMIS CLOUD FOUNDRY
cmis.server=https://api-sdm-di.cfapps.us10.hana.ondemand.com/
cmis.cliente.id=sb-dbecb33c-7e6e-43de-b9cf-bb0c0ac124bc!b273064|sdm-di-DocumentManagement-sdm_integration!b6332
cmis.cliente.secret=85436a42-5a7a-4760-9bb1-c0b33e49ddd3$iwubIhA5zNZdrYZSazhv1jWSBTffpogaxYTmugEImEU=
cmis.repository.id=282b35d7-5170-47c0-8912-2a56b389484a
cmis.server.credential=https://copeinca-com.authentication.us10.hana.ondemand.com

# IAS credentials - Identity Authentication Service
ias.api.url=https://avqfsmngl.accounts.ondemand.com/
ias.api.user=32472eaa-e163-43b5-8f22-3669079dcf18
ias.api.pass=jvkySGtpfr[2?94G-:rA[NNMuSjE6E.q

#URL CMIS MIGRACION
url.cmis.migracion = https://migracioncopeincaprof9iyf5gkk6.eu2.hana.ondemand.com/copeincaproviderapp/api/repositorio/getContentDocumentByIdCmis
