# PROFILE SPRING
spring.profiles.active=uaamock

#------------------------------------------------------------------------
#WAR COMPILE
##  mvn -P btp package install -Dspring.profiles.active=qas
#------------------------------------------------------------------------
#Deploy
##  cf push --vars-file vars-qas.yml
##  cf push --vars-file vars-prd.yml

# LOG
logging.config=classpath:logback-${spring.profiles.active}.xml

# BUILD DATETIME
war.build.datetime=1900/01/01_00:00

spring.output.ansi.enabled=ALWAYS

# multipartResolver
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.enabled=true

# enable/disable api-docs - swagger-ui
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html

# Packages to include
#springdoc.packagesToScan=com.package1, com.package2
springdoc.packagesToScan=com.incloud.hcp.rest.delta

# Paths to include
#springdoc.pathsToMatch=/v1, /api/balance/**
#springdoc.pathsToMatch=/v1/**, /api/**

#--------------------------------------------------------------
## Create the XSUAA Service Instance and Others
# Use the xs-security.json to define the authentication settings and create a service instance (once per btp environment)
# cf create-service xsuaa application xsuaa-copeincaprovider-authentication -c xs-security.json
# Create connectivity instance for JCO
# cf create-service connectivity lite jco-copeincaprovider-connectivity
# Create destination instance for JCO
# cf create-service destination lite jco-copeincaprovider-destination
#--------------------------------------------------------------