server.port=8086

# SETTING PORTAL
sm.portal.dev=true
sm.portal.nameId = 000000000
sm.portal.nameDisplay = Usuario Prueba
sm.portal.email = usuario@dominio.pe
log.proceso.enabled = true

#URL PORTAL
##CAMBIAR AQUI!!!
sm.portal.url = https://flpnwc-a8vkr95ktt.dispatcher.br1.hana.ondemand.com/sites/iprovider#Shell-home 
cfg.portal.url = https://flpnwc-cvbp7q70bv.dispatcher.br1.hana.ondemand.com/sites?siteId=dd9c5a9c-5852-408d-965c-14459df11b27#Shell-home

# CMIS
sm.portal.cmis.name = vendorRepositoryDev
sm.portal.cmis.key = vendorRepositoryDev
cfg.portal.cmis.name = iproviderRepositoryDev
cfg.portal.cmis.key = iproviderRepositoryDev
destination.cmis = IPROVIDER_CMIS

#Folder ECM
cfg.folder.ecm = ArchivosSunat

#ClaveSol
cfg.sunat.user = IPROVIDE
cfg.sunat.pass = iPROVIDE1

cfg.portal.url.public.oc = https://copeinca-com.launchpad.cfapps.us10.hana.ondemand.com/site?siteId=3d31aaf6-15cf-4509-969a-b5b3754404e4#Dynamic-display?sap-ui-app-id-hint=saas_approuter_iproviderpublicacionoccompras
cfg.portal.url.public.oc.proveedor = https://copeinca-com.launchpad.cfapps.us10.hana.ondemand.com/site?siteId=3d31aaf6-15cf-4509-969a-b5b3754404e4#Dynamic-display?sap-ui-app-id-hint=saas_approuter_iproviderpublicacionocprovee

#WEBSERVICE PDF-XML COMPROBATE DE RETENCION
cfg.retencion.ws.url = http://qas.incloud.la:9998/services/S3getFilesCopeinca

#NOTIFICACIONES CONSULTAS URL
cfg.notificacion.consulta.url = iprovider@copeinca.com.pe

# HANA (CLOUD) DB
# JPA / HIBERNATE
spring.jpa.properties.hibernate.format_sql=false
spring.datasource.driver-class-name=com.sap.db.jdbc.Driver
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.HANARowStoreDialect
spring.datasource.url = jdbc:sap://zeus.hana.prod.eu-central-1.whitney.dbaas.ondemand.com:24312/?user=IPROVIDER_DEV&currentSchema=IPROVIDER_DEV&password=Pa$$w0rd2020&encrypt=true&ValidateCertificate=true
spring.datasource.username = IPROVIDER_DEV
spring.datasource.password = Pa$$w0rd2020
destination.email = SEND_MAIL_IREQUEST

# PRIMARY DATA SOURCE
# HANA (CLOUD) DB
spring.jpa.hibernate.ddl-auto = none
spring.jta.enabled = true
spring.jpa.show-sql = true

# Hikari will use the above plus the following to setup connection pooling
spring.datasource.hikari.minimumIdle=2
spring.datasource.hikari.maximumPoolSize=10
spring.datasource.hikari.idleTimeout=3000
spring.datasource.hikari.poolName=SpringBootJPAHikariCP
spring.datasource.hikari.maxLifetime=20000
spring.datasource.hikari.connectionTimeout=3000

#destinations
destination.rfc.profit=SF_DEST_RFC

#CMIS CLOUD FOUNDRY
cmis.server=https://api-sdm-di.cfapps.us21.hana.ondemand.com/sss
cmis.cliente.id=sb-d7d4d3e6-d32c-4b2e-8f33-f343d3947927!b7982|sdm-di-DocumentManagement-sdm_integration!b171ss
cmis.cliente.secret=QJd2be9Ln0tBldvXBv0k1eUZ1z4=ss
cmis.repository.id=280a9cb5-a471-410b-a13b-ac8b3d974398sss
cmis.server.credential=https://bvn-prd-interno-cf-8pzu3hzg.authentication.us21.hana.ondemand.comsss

# IAS credentials - Identity Authentication Service
ias.api.url=https://avqfsmngl.accounts.ondemand.com/
ias.api.user=32472eaa-e163-43b5-8f22-3669079dcf18
ias.api.pass=jvkySGtpfr[2?94G-:rA[NNMuSjE6E.q

#URL CMIS MIGRACION
url.cmis.migracion = https://migracioncopeincaprof9iyf5gkk6.eu2.hana.ondemand.com/copeincaproviderapp/api/repositorio/getContentDocumentByIdCmis